### PR TITLE
Add exceptions

### PR DESCRIPTION
**Pull request by TenOs**

### CODE REVIEW

**Comment by rymir** [comment]
What is the benefit of using Exceptions instead of returning a bool? That you get a clear failure on the stacktrace?

I'm good with this, can we raise a pr to `https://github.com/Trax-air/swagger-parser` as soon as merging this?

**Comment by TenOs** [comment]
Exactly, the goal was to get an error so it can help us improve the swagger file.

I don't think we should raise a PR to `https://github.com/Trax-air/swagger-parser` because this is very specific to our needs. I've raised a PR for the bug fix when the dictionary only contains 1 element

**Comment by rymir** [comment]
I see, my concern is that by forking our own we miss bugfixes getting into upstream.

**Comment by Aeory** [comment]
I prefer raising an exception. We can easily add debugging information in
the exception, much like how "assertEquals" will add useful info. This is
harder to provide if we just check a boolean

**Pull request merged**
